version: "3.9"
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    image: flask
    container_name: flask
    restart: always
    ports:
      - 8080:8080

networks:
  mynetwork:
    driver: bridge
